### ISSUE TITLE
nimichereen should be nimichireen

### ISSUE THREAD

**Issue by danrs** [zacharyp/squad2xws#5]
Incorrect xws id as per title. I think I got the id wrong when I first added the new pilots to xws, which might have thrown you off.

You can see the incorrect id here: http://squad2xws.herokuapp.com/yasb/xws/?f=Resistance&d=v8ZsZ200Z448XWWW175WW&sn=Unnamed%20Squadron&obs=

**Comment by zacharyp** [comment]
Thanks for the bug submission, this is fixed now!  (Actually was fixed later that day)
