### ISSUE TITLE
Incorrect XWS ids

### ISSUE THREAD

**Issue by ToshioMagic** [zacharyp/squad2xws#9]
The following xws ids seem to be malformed when using the https://squad2xws.objectivecat.com/yasb/xws endpoint

contingencyprotocolsoc -> contingencyprotocol-siegeofcoruscant
strutlockoverridesoc -> strutlockoverride-siegeofcoruscant
ancillaryionweaponssoc -> ancillaryionweapons-siegeofcoruscant
l337sprogrammingboy -> l337sprogramming-battleofyavin

**Comment by zacharyp** [comment]
this was fixed via https://github.com/zacharyp/squad2xws/pull/10
